version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:7.2.0-v7
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
